In [5]:
del d

In [4]:

d=dict(a=1, b=2)
d = {}
d

{}

In [9]:
d={'a':64, 'b':65, 'c':66, 'd':67}
print(d.keys())

dict_keys(['a', 'b', 'c', 'd'])


In [10]:
d.values()

dict_values([64, 65, 66, 67])

In [17]:
dict_1 = {"Python":40, "R":45}

In [20]:
dict_1

{'Python': 40}

In [19]:
del dict_1['R']

In [22]:
s=input()
a = s.split('')
a

ab#ab#ab6a


ValueError: empty separator

In [23]:
#input has been taken for you
s=input()

#start writing your code to check if s is upgrad string or no
d = {}

for item in s:
    if item not in d:
        d[item] = 1
    else: 
        d[item] = d[item] + 1

print(d.values())

ab#ab#ab6a
dict_values([4, 3, 2, 1])


In [46]:
import ast,sys
input_str = ["pasta","pasta","pasta","paratha","paratha","paratha"]
votes = input_str

d = {}

for vote in votes:
    if vote not in d:
        d[vote] = 1
    else:
        d[vote] = d[vote] + 1

vals = d.values()
m = 0
n = len(input_str) / 2
# print(n)
for i in d:
    if d[i]>n:
        m = 1
        n = 
if (m == 1)
    print

3.0
NOTA
NOTA


In [50]:
d

{'pasta': 3, 'paratha': 3}

In [51]:
for i in d:
    print(d.keys())

dict_keys(['pasta', 'paratha'])
dict_keys(['pasta', 'paratha'])


In [ ]:
print()

In [56]:
import statistics 
from statistics import mode 

In [59]:
List = [2, 1, 2, 2, 1, 3, 3, 3]

In [62]:
if(mode(List)):
   print('No mode!')

StatisticsError: no unique mode; found 2 equally common values

In [28]:
import ast,sys
input_str = ["pasta","pasta","pasta", "pasta", "paratha","paratha","paratha"]
votes = input_str

d = {}

for vote in votes:
    if vote not in d:
        d[vote] = 1
    else:
        d[vote] = d[vote] + 1
        
count = 0
n = int(len(input_str) / 2)
vals = d.values()

for k, v in d.items():
    if v > n:
        keyy = k
        count += 1
        break

if count > 0:
    print(keyy)
else:
    print("NOTA")

pasta


In [29]:
n

3

In [33]:
a = [[1,2,3],[4,5,6]]

In [35]:
import numpy as np

In [37]:
a = np.zeros((2, 3))

In [39]:
a[ : , :2]

SyntaxError: invalid syntax (<ipython-input-39-4d0552a55b24>, line 1)

In [ ]:
def interchangeFirstLast(mat, n, m): 
    rows = n 
      
    # swapping of element between 
    # first and last rows 
    for i in range(n): 
        t = mat[0][i] 
        mat[0][i] = mat[rows-1][i] 
        mat[rows-1][i] = t 
        

In [48]:
rows = a.shape[0]
cols = a.shape[1]
def changemandnthrow(a, m, n):
    for i in range(0, cols):
        temp = a[m][i]
        a[m][i] = a[n][i]
        a[n][i] = temp

changemandnthrow(a, 0, 2)
print(a)
        

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]


In [45]:
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])
a#.shape[1]

array([[4, 3, 1],
       [5, 7, 0],
       [9, 9, 3],
       [8, 2, 4]])

In [41]:
a

array([[4, 3, 1],
       [5, 7, 0],
       [9, 9, 3],
       [8, 2, 4]])

In [52]:
a = np.zeros([n, n], dtype = int)

In [54]:
np.shape(a)

(2, 2)